const products=[
    {
        productId:"1",
        title:"Apple",
        price:"55000",
        category:["mobile","electronics"],
        companyId:"101",
        sellerId:["201","202"]
    },
    {
        productId:"2",
        title:"Microwave",
        price:"8000",
        category:["electronics","kitchen"],
        companyId:"102",
        sellerId:["202","204"]
    },
    {
        productId:"3",
        title:"Gold Chain",
        price:"48000",
        category:["jewelry","gold"],
        companyId:"103",
        sellerId:["210","211"]
    },
    {
        productId:"3",
        title:"Gold Ring",
        price:"48000",
        category:["jewelry","gold"],
        companyId:"104",
        sellerId:["210","211"]
    },
    {
        productId:"5",
        title:"Gold Bracelet",
        price:"59000",
        category:["jewelry","gold"],
        companyId:"103",
        sellerId:["211"]
    },
    {
        productId:"6",
        title:"TestC",
        price:"59000",
        category:["jewelry","gold"],
        companyId:"123",
        sellerId:["211"]
    },
    {
        productId:"6",
        title:"TestF",
        price:"59000",
        category:["jewelry","gold"],
        companyId:"",
        sellerId:["211"]
    }
];

module.exports=products;