const seller=[
    {
        sellerId:"201",
        name:"Bhavya",
        productId:["1"]
    },
    {
        sellerId:"202",
        name:"Meet",
        productId:["1","2"]
    },
    {
        sellerId:"204",
        name:"Yash",
        productId:["2"]
    },
    {
        sellerId:"210",
        name:"Krunal",
        productId:["3"]
    },
    {
        sellerId:"211",
        name:"Jainam",
        productId:["3","5"]
    }
];

module.exports=seller;